#!/bin/bash -l
 
#BSUB -P cryoem
#BSUB -J XXXnameXXX
#BSUB -q XXXqueueXXX
#BSUB -n XXXmpinodesXXX
#BSUB -gpu "num=XXXextra4XXX:mode=exclusive_process:j_exclusive=no:mps=no"
#BSUB -W XXXextra1XXX
#BSUB -e XXXerrfileXXX
#BSUB -o XXXoutfileXXX
#BSUB XXXextra5XXX
#BSUB -B
 
# other
# threads: XXXthreadsXXX
# cores: XXXcoresXXX
# dedicated: span[ptile=XXXdedicatedXXX]
# mem: XXXextra2XXX
# unused: XXXextra3XXX

# setup environment
source /etc/profile.d/modules.sh
export MODULEPATH=/usr/share/Modules/modulefiles:/opt/modulefiles:/afs/slac/package/singularity/modulefiles
module purge
module load PrgEnv-gcc
module load relion/3.0.2

# set tmpdir for relion
export TMPDIR=/scratch/${USER}/${LSB_JOBID}/TMPDIR/

# run relion
mpirun --mca btl tcp,self  XXXcommandXXX 
