TAG=292.0.0-alpine
PREFIX=/afs/slac/package/singularity/images/
IMAGE=google/cloud-sdk
NAME=google-sdk

singularity:
	singularity pull -F ${PREFIX}/${NAME}/${TAG}/${NAME}@${TAG}.sif docker://${IMAGE}:${TAG}
