#!/bin/bash -l
 
#BSUB -P cryoem
#BSUB -J XXXnameXXX
#BSUB -q XXXqueueXXX
#BSUB -n XXXmpinodesXXX
#BSUB -gpu "num=1:mode=exclusive_process:j_exclusive=no:mps=no"
#BSUB -R "span[hosts=1]"
#BSUB -W XXXextra1XXX
#BSUB -e XXXerrfileXXX
#BSUB -o XXXoutfileXXX
#BSUB -B
 
# setup environment
source /etc/profile.d/modules.sh
export MODULEPATH=/usr/share/Modules/modulefiles:/opt/modulefiles:/afs/slac/package/singularity/modulefiles
module purge
module load PrgEnv-gcc/4.8.5
module load relion/2.1

# set tmpdir for relion
export TMPDIR=/scratch/${USER}/${LSB_JOBID}/TMPDIR/

# run relion
mpirun --mca btl tcp,self  XXXcommandXXX 
